version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopagolic-productcatalog
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - '8080:8080'

  mongo:
    container_name: shopagolic-productcatalog-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - shopagolic-productcatalog-mongo-data:/data/db

  #  mongo-seed:
  #    container_name: mflix-mongo-seed
  #    image: mongo
  #    depends_on:
  #      - mongo
  #    volumes:
  #      - ./data/mflix_dump/:/data/mflix
  #    command: >
  #      bash -c "mongorestore --host mongo:27017 -v --drop /data/mflix/comments.bson
  #      && mongorestore --host mongo:27017 -v --drop /data/mflix/movies.bson
  #      && mongorestore --host mongo:27017 -v --drop /data/mflix/users.bson
  #      && mongorestore --host mongo:27017 -v --drop /data/mflix/sessions.bson"

  mongo-express:
    container_name: shopagolic-productcatalog-mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"

volumes:
  shopagolic-productcatalog-mongo-data:
