version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopagolic-cart
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - '8080:8080'

  redis:
    container_name: shopagolic-cart-redis
    image: redis:7.0.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - shopagolic-cart-redis-data:/data

volumes:
  shopagolic-cart-redis-data:
