version: '3'
services:
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      - REDIS_ADDR=test-redis:6379
      - GRPC_ADDR=test-app:8080
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    depends_on:
      - test-app
    command: |
      go test -count 1 -v ./test/...

  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-shopagolic-cart
    environment:
      - REDIS_ADDR=test-redis:6379
    depends_on:
      - test-redis

  test-redis:
    container_name: test-shopagolic-cart-redis
    image: redis:7.0.4-alpine
