version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopagolic-shipping
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - '8080:8080'
