version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopagolic-currency
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - '8080:8080'

  redis:
    container_name: shopagolic-currency-redis
    image: redis:7.0.4-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - shopagolic-currency-redis-data:/data

volumes:
  shopagolic-currency-redis-data:
